kind: Service
apiVersion: v1
metadata:
  name: rag-interface-service
  namespace: azure-iot-operations
  labels:
    app: rag-interface-dapr-workload
spec:
  selector:
    app: rag-interface-dapr-workload
  ports:
    - protocol: TCP
      port: 8701
      targetPort: 8701
  type: LoadBalancer